# Generated by Django 5.0.1 on 2024-02-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categoria_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='imagen',
            new_name='imagen_cat',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='imagen',
            new_name='imagen_post',
        ),
    ]
