# Generated by Django 5.0.1 on 2024-02-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_categoria_url_redireccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='url_categorias',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
