# Generated by Django 5.0.1 on 2024-02-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_categoria_url_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', null=True, unique=True),
        ),
    ]
