# Generated by Django 5.0.1 on 2024-02-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_carrito_itemcarrito_carrito_productos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name_plural': 'Categoria'},
        ),
    ]
