# Generated by Django 5.0.1 on 2024-02-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_imagen_categoria_imagen_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
