# Generated by Django 5.0.1 on 2024-02-19 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_categoria_url_redireccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='url_redireccion',
        ),
    ]
