# Generated by Django 5.0.1 on 2024-02-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_categoria_url_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='url_categorias',
        ),
    ]
