# Generated by Django 5.1.7 on 2026-04-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('efectivo', 'Efectivo al retirar'), ('tarjeta', 'Tarjeta de crédito')], default='transferencia', max_length=20),
        ),
    ]
