# Generated by Django 5.1.7 on 2026-05-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_orden_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orden',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='orden',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orden',
            name='mp_estado_pago',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orden',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orden',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orden',
            name='provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orden',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
