# Generated by Django 5.1.7 on 2026-05-12 03:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_orden_ciudad_orden_codigo_postal_orden_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margen_ganancia', models.DecimalField(decimal_places=2, default=30, help_text='Margen de ganancia global en %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('iva', models.CharField(choices=[('0', '0% — Exento'), ('10.5', '10.5% — Tasa reducida'), ('21', '21% — Tasa general')], default='21', max_length=5)),
                ('recargo_tarjeta', models.DecimalField(decimal_places=2, default=0, help_text='Recargo por pago con tarjeta de crédito en %', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('transporte', models.DecimalField(decimal_places=2, default=0, help_text='Costo de transporte fijo por defecto (en $)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Configuración global',
                'verbose_name_plural': 'Configuración global',
            },
        ),
        migrations.CreateModel(
            name='PromocionBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('descuento', 'Descuento'), ('cuotas', 'Cuotas sin interés')], default='descuento', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, help_text='% de descuento o cantidad de cuotas según tipo', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Promoción bancaria',
                'verbose_name_plural': 'Promociones bancarias',
                'ordering': ['-activo', 'banco', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionCategoriaCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margen_ganancia', models.DecimalField(decimal_places=2, help_text='Margen de ganancia para esta categoría en %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('iva', models.CharField(blank=True, choices=[('0', '0% — Exento'), ('10.5', '10.5% — Tasa reducida'), ('21', '21% — Tasa general')], help_text='IVA específico para esta categoría (vacío = usar global)', max_length=5)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_costo', to='tienda.categorias')),
            ],
            options={
                'verbose_name': 'Config. costo por categoría',
                'verbose_name_plural': 'Config. costos por categoría',
            },
        ),
        migrations.CreateModel(
            name='CostoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_neto', models.DecimalField(decimal_places=2, default=0, help_text='Costo de compra al proveedor sin IVA', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descuento_proveedor', models.DecimalField(decimal_places=2, default=0, help_text='Descuento otorgado por el proveedor en %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('impuesto_interno', models.DecimalField(decimal_places=2, default=0, help_text='Impuesto interno adicional en %', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('transporte', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de transporte en $ (vacío = usar global)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('margen_ganancia', models.DecimalField(blank=True, decimal_places=2, help_text='Margen de ganancia en % (vacío = usar categoría o global)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('iva', models.CharField(blank=True, choices=[('0', '0% — Exento'), ('10.5', '10.5% — Tasa reducida'), ('21', '21% — Tasa general')], help_text='IVA de este producto (vacío = usar categoría o global)', max_length=5)),
                ('descuento_promocion', models.DecimalField(decimal_places=2, default=0, help_text='Descuento promocional al consumidor final en %', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recargo_tarjeta', models.DecimalField(blank=True, decimal_places=2, help_text='Recargo tarjeta de crédito en % (vacío = usar global)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costo', to='tienda.productos')),
            ],
            options={
                'verbose_name': 'Costo de producto',
                'verbose_name_plural': 'Costos de productos',
            },
        ),
    ]
