# Generated by Django 5.0.1 on 2024-02-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_productos_imagen_productoimagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimagen',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_producto', to='tienda.productos'),
        ),
    ]
