# Generated by Django 5.0.1 on 2024-02-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_productoimagen_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='imagenes',
        ),
    ]
