# Generated by Django 5.0.1 on 2024-02-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_productos_imagen_productos_imagen2_productos_imagen3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='tienda_images/productos'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen2',
            field=models.ImageField(null=True, upload_to='tienda_images/productos'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen3',
            field=models.ImageField(null=True, upload_to='tienda_images/productos'),
        ),
    ]
